# Использование команд библиотеки NumPy

In [4]:
import numpy as np

## 1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [5]:
my_array = np.arange(0, 100, 5)
print(my_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


## 2. Из полученного массива получить массив с кратными 10 числами

In [6]:
my_array_multiple_by_10 = my_array[my_array % 10 == 0]
print(my_array_multiple_by_10)

[ 0 10 20 30 40 50 60 70 80 90]


## 3. Получить двумерный массив с двумя столбцами

In [7]:
two_dimension_array = my_array_multiple_by_10.reshape(-1, 2)
print(two_dimension_array)

[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]


## 4. Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [8]:
my_second_array = two_dimension_array - 5
print(my_second_array)

[[-5  5]
 [15 25]
 [35 45]
 [55 65]
 [75 85]]


## 5. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [9]:
combined34_array = (np.hstack((two_dimension_array, my_second_array),dtype=float))
print(combined34_array)

[[ 0. 10. -5.  5.]
 [20. 30. 15. 25.]
 [40. 50. 35. 45.]
 [60. 70. 55. 65.]
 [80. 90. 75. 85.]]


## 6. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [11]:
combined34_array.T[1] = (combined34_array.T[1] / combined34_array.T[0].reshape(-1, 5))
combined34_array.T[2] = (combined34_array.T[2] / combined34_array.T[1].reshape(-1, 5))
combined34_array.T

array([[ 0.00000000e+00,  2.00000000e+01,  4.00000000e+01,
         6.00000000e+01,  8.00000000e+01],
       [            inf,  7.50000000e-02,  3.12500000e-02,
         1.94444444e-02,  1.40625000e-02],
       [-0.00000000e+00,  1.33333333e+02,  8.96000000e+02,
         2.42448980e+03,  4.74074074e+03],
       [ 5.00000000e+00,  2.50000000e+01,  4.50000000e+01,
         6.50000000e+01,  8.50000000e+01]])

## 7. Оставить только те значения, которые не изменились после деления

In [12]:
not_changed_array = np.delete(combined34_array, [1,2], axis=1)
not_changed_array.T

array([[ 0., 20., 40., 60., 80.],
       [ 5., 25., 45., 65., 85.]])

## 8. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [14]:
ar_ray = np.delete(combined34_array, 2, axis=1)
ar_ray = ar_ray.T
ar_ray

array([[0.00000000e+00, 2.00000000e+01, 4.00000000e+01, 6.00000000e+01,
        8.00000000e+01],
       [           inf, 7.50000000e-02, 3.12500000e-02, 1.94444444e-02,
        1.40625000e-02],
       [5.00000000e+00, 2.50000000e+01, 4.50000000e+01, 6.50000000e+01,
        8.50000000e+01]])

In [15]:
ar_ray[[0,2]] = ar_ray[[2,0]]
ar_ray

array([[5.00000000e+00, 2.50000000e+01, 4.50000000e+01, 6.50000000e+01,
        8.50000000e+01],
       [           inf, 7.50000000e-02, 3.12500000e-02, 1.94444444e-02,
        1.40625000e-02],
       [0.00000000e+00, 2.00000000e+01, 4.00000000e+01, 6.00000000e+01,
        8.00000000e+01]])

## 9. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [16]:
mean_array = np.mean(ar_ray, axis=1)
print(mean_array)

[45. inf 40.]


In [17]:
median_array = np.median(ar_ray, axis=1)
print(median_array)

[4.500e+01 3.125e-02 4.000e+01]


In [18]:
std_array = np.median(ar_ray, axis=1)
print(std_array)

[4.500e+01 3.125e-02 4.000e+01]


## 10. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

In [20]:
max_vals = np.max(ar_ray, axis=1)
normalized_for_max = ar_ray / max_vals[:, np.newaxis]
normalized_for_max

C:\Users\Wharton\AppData\Local\Temp\ipykernel_11856\3581989803.py:2: RuntimeWarning: invalid value encountered in divide
  normalized_for_max = ar_ray / max_vals[:, np.newaxis]


array([[0.05882353, 0.29411765, 0.52941176, 0.76470588, 1.        ],
       [       nan, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.5       , 0.75      , 1.        ]])

# Использование команд библиотеки pandas

In [3]:
import pandas as pd

## 1. Импортируйте данные из файла “Global Population Trends(2016-2022).csv”

In [4]:
df = pd.read_csv('Global Population Trends(2016-2022).csv')

## 2. Считайте несколько первых записей таблицы (head())

In [5]:
df.head(7)

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
5      Albania  2017                -                -                -   
6      Albania  2018        2,866,376        1,728,969        1,137,407   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   
5                105              79      10.870       8.150          1.491   
6                105              79      10.517       8.308           1.44   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3  
5                   8.3           -  
6                   8.3           0

## 3. Определите размерность данного фрейма (shape())

In [6]:
df.shape

(1073, 12)

## 4. Выведите название заголовков столбцов фрейма (columns)

In [7]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

## 5. Получите описание всех переменных (полей) (info())

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


## 6. Удалите строки, не содержащие значения в столбце «Total Population» 

In [9]:
df_with_total_population_data = df[df['Total Population'] != '-']
df_with_total_population_data

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

## 7. Получите описательную статистику по переменным (например, max(), min(), describe())

In [10]:
df_with_total_population_data.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

In [11]:
df_with_total_population_data.max()

Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                  85
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                       5
dtype: object

In [12]:
df_with_total_population_data.min()

Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                       -1
dtype: object

## 8. Выполните сортировку данных по нескольким критериям

In [13]:
df_with_total_population_data.sort_values(by='Year', ascending=True)

Country  Year Total Population Urban Population Rural Population  \
1        Afghanistan  2018       36,686,784        9,353,296       27,333,488   
1014  United Kingdom  2018       66,460,344       55,426,598       11,033,746   
227             Cuba  2018       11,328,244        8,726,939        2,601,305   
602       Mauritania  2018        4,270,712        2,292,177        1,978,535   
232          Curacao  2018          159,336          142,040           17,296   
...              ...   ...              ...              ...              ...   
555        Lithuania  2021        2,800,839        1,911,545          889,294   
550    Liechtenstein  2021           39,039            5,649           33,390   
545            Libya  2021        6,735,277        5,455,170        1,280,107   
585         Maldives  2021          521,457          214,329          307,128   
1072        Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
1014                275              81      11.000       9.200   
227                 109              77      10.348       9.815   
602                   4              65      34.183       7.248   
232                 359               0      10.500       8.800   
...                 ...             ...         ...         ...   
555                   -              74       8.300      17.000   
550                   -              84       9.600       6.900   
545                   -              72      17.828       6.018   
585                   -              80      14.088       3.020   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
1014           1.68                   3.8           1  
227           1.631                   4.2           0  
602           4.607                  34.7           3  
232             1.7                     -          -1  
...             ...                   ...         ...  
555            1.34                   2.7           0  
550            1.53                     -           1  
545           2.462                   9.2           1  
585           1.692                   5.1           1  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

## 9. Выведите название страны, которая имеет максимальную численность населения

In [43]:
max_population_country = df[df['Total Population'] == df['Total Population'].max()]

print(max_population_country[['Country', 'Total Population']])

# def convert_population(population_str):
#     try:
#         return int(population_str.replace(',', '').replace('-', '0'))
#     except ValueError:
#         return 0
# 
# # Преобразование столбца "Total Population" в числовой формат
# df['Total Population'] = df['Total Population'].map(convert_population)
# 
# # Находим максимальное значение в столбце "Total Population"
# max_population = df['Total Population'].max()
# 
# # Фильтруем строки с максимальным населением
# max_population_country = df[df['Total Population'] == max_population]
# 
# # Выводим результат
# print("Максимальное население:", max_population)
# print(max_population_country[['Country', 'Total Population']])

    Country  Total Population
205   China        1412360000


## 10. Выведите название страны, которая имеет минимальную численность населения

In [44]:
min_population_country = df_with_total_population_data[df_with_total_population_data['Total Population'] == df_with_total_population_data['Total Population'].min()]

print(min_population_country[['Country', 'Total Population']])

    Country  Total Population
994  Tuvalu             10865


## 11. Экспорт фрейма в MS Excel 

In [42]:
df_with_total_population_data.to_excel('population.xlsx', index=False)