In [1]:
import os
os.listdir('aclImdb')

['imdb.vocab', 'imdbEr.txt', 'README', 'test', 'train', 'unsup']

In [2]:
from sklearn.datasets import load_files
reviews_train = load_files('aclImdb/train/')
text_train, y_train = reviews_train.data, reviews_train.target

In [3]:
print("type of text_train: {}".format(type(text_train)))
print("length of text_train: {}".format(len(text_train)))
print("text_train[1]:\n{}".format(text_train[1]))

type of text_train: <class 'list'>
length of text_train: 25000
text_train[1]:
b'Words can\'t describe how bad this movie is. I can\'t explain it by writing only. You have too see it for yourself to get at grip of how horrible a movie really can be. Not that I recommend you to do that. There are so many clich\xc3\xa9s, mistakes (and all other negative things you can imagine) here that will just make you cry. To start with the technical first, there are a LOT of mistakes regarding the airplane. I won\'t list them here, but just mention the coloring of the plane. They didn\'t even manage to show an airliner in the colors of a fictional airline, but instead used a 747 painted in the original Boeing livery. Very bad. The plot is stupid and has been done many times before, only much, much better. There are so many ridiculous moments here that i lost count of it really early. Also, I was on the bad guys\' side all the time in the movie, because the good guys were so stupid. "Executive Decisio

In [4]:
text_train = [doc.replace(b"<br />", b" ") for doc in text_train]

In [5]:
print("text_train[1]:\n{}".format(text_train[1]))

text_train[1]:
b'Words can\'t describe how bad this movie is. I can\'t explain it by writing only. You have too see it for yourself to get at grip of how horrible a movie really can be. Not that I recommend you to do that. There are so many clich\xc3\xa9s, mistakes (and all other negative things you can imagine) here that will just make you cry. To start with the technical first, there are a LOT of mistakes regarding the airplane. I won\'t list them here, but just mention the coloring of the plane. They didn\'t even manage to show an airliner in the colors of a fictional airline, but instead used a 747 painted in the original Boeing livery. Very bad. The plot is stupid and has been done many times before, only much, much better. There are so many ridiculous moments here that i lost count of it really early. Also, I was on the bad guys\' side all the time in the movie, because the good guys were so stupid. "Executive Decision" should without a doubt be you\'re choice over this one, even

In [6]:
import numpy as np
np.unique(y_train)

array([0, 1])

In [7]:
print("Количество примеров на класс (обучение - training: {}".format(np.bincount(y_train)))

Количество примеров на класс (обучение - training: [12500 12500]


In [8]:
reviews_train = load_files('aclImdb/test/')
text_test, y_test =reviews_train.data, reviews_train.target
print("Количество документов в текстовых данных: {}".format(len(text_test)))

Количество документов в текстовых данных: 25000


In [9]:
print("Количество примеров на класс (тест - test): {}".format(np.bincount(y_test)))

Количество примеров на класс (тест - test): [12500 12500]


In [10]:
text_test = [doc.replace(b"<br />", b" ") for doc in text_test]

In [11]:
bards_words = ["The fool doth think he is wise,",
               "but the wise man knows himself to be a fool"]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
vect.fit(bards_words)

CountVectorizer()

In [13]:
print("Size of the dict: {}".format(len(vect.vocabulary_)))
print("Inhalt of the dict: \n {}".format(vect.vocabulary_))

Size of the dict: 13
Inhalt of the dict: 
 {'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [14]:
bag_of_words = vect.transform(bards_words)
print("bag_of_words: {}".format(repr(bag_of_words)))

bag_of_words: <2x13 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>


In [15]:
print("Плотное представление bag_of_words: \n {}".format(bag_of_words.toarray()))

Плотное представление bag_of_words: 
 [[0 0 1 1 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 0 1 0 1 1 1 0 1 1]]


In [16]:
vect = CountVectorizer(max_features=1000, max_df=.15, min_df=5).fit(text_train)
X_train = vect.transform(text_train)

In [17]:
print("X_train:\n {}".format(repr(X_train)))

X_train:
 <25000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1102586 stored elements in Compressed Sparse Row format>


In [18]:
vect

CountVectorizer(max_df=0.15, max_features=1000, min_df=5)

In [19]:
feature_names = vect.get_feature_names_out()
print("Количество признаков: {}".format(len(feature_names)))
print("Первые 20 признаков: \n {}".format(feature_names[:20]))
print("Признаки с 201 по 230 \n{}".format(feature_names[201:230]))
print("Каждый 200-признак:\n {}".format(feature_names[::200]))

Количество признаков: 1000
Первые 20 признаков: 
 ['10' '15' '20' '30' '80' '90' 'able' 'above' 'absolutely' 'across' 'act'
 'acted' 'action' 'actor' 'actors' 'actress' 'actual' 'actually' 'add'
 'admit']
Признаки с 201 по 230 
['dead' 'deal' 'death' 'decent' 'decided' 'decides' 'deep' 'definitely'
 'depth' 'deserves' 'despite' 'development' 'dialog' 'dialogue' 'didn'
 'die' 'died' 'different' 'difficult' 'directed' 'directing' 'direction'
 'director' 'directors' 'disappointed' 'disney' 'doctor' 'documentary'
 'doesn']
Каждый 200-признак:
 ['10' 'de' 'having' 'office' 'song']


In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [21]:
scores = cross_val_score(LogisticRegression(), X_train, y_train, cv=5)
print("Mean value of cross_val_score: {:.2f}".format(np.mean(scores)))

Mean value of cross_val_score: 0.84


In [22]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(max_iter=100), param_grid, cv=5)
grid.fit(X_train, y_train)
print("The best cross_val: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)

The best cross_val: 0.84
Best parameters:  {'C': 0.01}


In [23]:
X_test = vect.transform(text_test)

In [24]:
print("The best score on test set: {:.2f}".format(grid.score(X_test, y_test)))

The best score on test set: 0.85


In [25]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
print("Количество стоп-слов: {}".format(len(ENGLISH_STOP_WORDS)))
print("Every 10th word: \n{}".format(list(ENGLISH_STOP_WORDS)[::10]))

Количество стоп-слов: 318
Every 10th word: 
['him', 'there', 'now', 'hereupon', 'again', 'cannot', 'somehow', 'mostly', 'anything', 'well', 'two', 'seeming', 'everything', 'some', 'those', 'co', 'sixty', 'bill', 'yourself', 'however', 'or', 'to', 'down', 'go', 'except', 'could', 'how', 'than', 'etc', 'whither', 'beyond', 'within']


In [26]:
vect = CountVectorizer(max_features=1000, min_df=5, stop_words='english').fit(text_train)
X_train = vect.transform(text_train)
print("X_train with stop-words: \n {}".format(repr(X_train)))

X_train with stop-words: 
 <25000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1158150 stored elements in Compressed Sparse Row format>
