In [2]:
import numpy as np

In [3]:
a = np.array([1, 3, 6])
a

array([1, 3, 6])

In [4]:
b = np.array([[1.5, 3.7], [5.1, 7.3]])
b

array([[1.5, 3.7],
       [5.1, 7.3]])

In [6]:
c = np.array([[1, 3, 5], [2, 4, 6]])
c

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
d = np.array(((9, 8, 7), (3, 4, 5)))
d

array([[9, 8, 7],
       [3, 4, 5]])

In [8]:
e = np.array([(1, 4, 7), [2, 5, 8], (3, 6, 9)])
e

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
f = np.array(((11, 13, 15), (12, 14, 16)), dtype=float)
f

array([[11., 13., 15.],
       [12., 14., 16.]])

In [10]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.arange(1, 16, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [15]:
np.arange(0, 3, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [17]:
np.arange(0, 8).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
np.linspace(1, 7, 14)

array([1.        , 1.46153846, 1.92307692, 2.38461538, 2.84615385,
       3.30769231, 3.76923077, 4.23076923, 4.69230769, 5.15384615,
       5.61538462, 6.07692308, 6.53846154, 7.        ])

In [19]:
np.random.random(5)

array([0.8977102 , 0.20526599, 0.99138331, 0.10489494, 0.18683031])

In [20]:
np.random.random((3, 5))

array([[0.63412773, 0.27000437, 0.36778859, 0.89242471, 0.44010128],
       [0.26894046, 0.07438179, 0.44947661, 0.52168409, 0.61195125],
       [0.18688905, 0.15970041, 0.24242518, 0.54566124, 0.54329001]])

In [22]:
g = np.array(((1, 4, 7), (2, 5, 8), (3, 6, 9)))
g

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
g[::-1]

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [24]:
g[:,2]

array([7, 8, 9])

In [25]:
g[1, 2] = 11
g

array([[ 1,  4,  7],
       [ 2,  5, 11],
       [ 3,  6,  9]])

In [27]:
for i in g:
    print(i ** 3)

[  1  64 343]
[   8  125 1331]
[ 27 216 729]


In [28]:
li_st = [1, 3, 5, 7, 9]
ar_ray = np.array(li_st)
print(ar_ray)
print(ar_ray.dtype)
type(ar_ray)

[1 3 5 7 9]
int32


numpy.ndarray

In [30]:
h = np.array([[1, 3, 13], [5, 7, 15]])
h.shape

(2, 3)

In [31]:
i = np.array([[0, 10, 20], [100, 90, 80]])
i

array([[  0,  10,  20],
       [100,  90,  80]])

In [34]:
li_st2 = [1, 11, 21, 31, 41]
ar_ray2 = np.array(li_st2)

for i in range(len(li_st2)):
    li_st2[i] += 1
ar_ray2 += 1

print(li_st2)
print(ar_ray2)

for i in range(len(li_st2)):
    li_st2[i] -= 2
ar_ray2 -= 2

print(li_st2)
print(ar_ray2)

[2, 12, 22, 32, 42]
[ 2 12 22 32 42]
[0, 10, 20, 30, 40]
[ 0 10 20 30 40]


In [36]:
zeros = np.zeros(7)
ones = np.ones(7)
ara_nge = np.arange(7)
lin_space = np.linspace(0, 1, 3)

print(zeros)
print(ones)
print(ara_nge)
print(lin_space)

print(ones + ara_nge)
print(ones * ara_nge)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6]
[0.  0.5 1. ]
[1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6.]


In [51]:
print(np.arange(7)[3:5])

ara_nge2 = np.arange(15).reshape(3, 5)

print(ara_nge2, '\n')
print(ara_nge2[:,3:], '\n')
print(ara_nge[ara_nge % 2 == 1], '\n')
print(ara_nge2.shape, '\n')

ara_nge3 = ara_nge2[np.newaxis, :]
print(ara_nge3.shape, '\n')
print(ara_nge3)

[3 4]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 3  4]
 [ 8  9]
 [13 14]] 

[1 3 5] 

(3, 5) 

(1, 3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


In [3]:
import pandas as pd

In [53]:
df = pd.DataFrame({'int_col': [1, 3, 5, 7, -9],
                   'float_col': [0.1, 0.3, 0.5, 0.7, 0.9],
                   'str_col': 
                       ['abc', 'def', 'ghi', 'jkl', 'mno']
                   })
df

int_col  float_col str_col
0        1        0.1     abc
1        3        0.3     def
2        5        0.5     ghi
3        7        0.7     jkl
4       -9        0.9     mno

In [54]:
countries = {"name": ["Russia", "USA", "China", "India"],
             "area": [1, 3, 4, 7],
             "population": [9, 3, 1, 2]}
country_frame = pd.DataFrame(countries,
                columns = ['area', 'population'],
                index = countries["name"])
print(country_frame)

        area  population
Russia     1           9
USA        3           3
China      4           1
India      7           2


In [3]:
df2 = pd.read_csv('people-example.csv')
df2

First Name  Last Name   Country  Age
0    Michael     Jordan       USA   46
1       Dirk   Nowitzki   Germany   51
2       Luka     Doncic  Slovenia   24
3     Andrei  Kirilenko    Russia   52
4       Rudy     Gobert    France   31

In [4]:
df3 = pd.read_excel('people-example.xlsx')
df3

First Name  Last Name   Country  Age
0    Michael     Jordan       USA   46
1       Dirk   Nowitzki   Germany   51
2       Luka     Doncic  Slovenia   24
3     Andrei  Kirilenko    Russia   52
4       Rudy     Gobert    France   31
5      James     Harden       USA   34

In [7]:
df3.head(3)

First Name Last Name   Country  Age
0    Michael    Jordan       USA   46
1       Dirk  Nowitzki   Germany   51
2       Luka    Doncic  Slovenia   24

In [5]:
df3.columns

Index(['First Name', 'Last Name', 'Country', 'Age'], dtype='object')

In [6]:
df3.describe()

Age
count   6.000000
mean   39.666667
std    11.604597
min    24.000000
25%    31.750000
50%    40.000000
75%    49.750000
max    52.000000

In [7]:
df3.describe(include=["object", "bool"])

First Name Last Name Country
count           6         6       6
unique          6         6       5
top       Michael    Jordan     USA
freq            1         1       2

In [8]:
df3.Country.value_counts()

Country
USA         2
Germany     1
Slovenia    1
Russia      1
France      1
Name: count, dtype: int64

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   First Name  6 non-null      object
 1   Last Name   6 non-null      object
 2   Country     6 non-null      object
 3   Age         6 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes


In [10]:
print(df3['First Name'].to_list())

['Michael', 'Dirk', 'Luka', 'Andrei', 'Rudy', 'James']


In [11]:
df3.sort_values(by="Country", ascending=False)
df3.head()

First Name  Last Name   Country  Age
0    Michael     Jordan       USA   46
1       Dirk   Nowitzki   Germany   51
2       Luka     Doncic  Slovenia   24
3     Andrei  Kirilenko    Russia   52
4       Rudy     Gobert    France   31

In [12]:
df3['Age'].sum()

238

In [13]:
df3.groupby(['First Name']).sum()

Last Name   Country  Age
First Name                          
Andrei      Kirilenko    Russia   52
Dirk         Nowitzki   Germany   51
James          Harden       USA   34
Luka           Doncic  Slovenia   24
Michael        Jordan       USA   46
Rudy           Gobert    France   31

In [14]:
df3.groupby(['First Name']).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [15]:
print(df3[df3['Country'] == 'USA'])
print(df3[(df3['Country'] == 'USA') & (df3['Age'] == 34)])

  First Name Last Name Country  Age
0    Michael    Jordan     USA   46
5      James    Harden     USA   34
  First Name Last Name Country  Age
5      James    Harden     USA   34
